package koto
PROJECT_NAME :: "KT Game"
PROJECT_VERSION :: 0
RENDER_FRAME_IN_FLIGHT :: 2
RENDER_FIXED_UPDATE_FREQUENCY :: 60
RENDER_FIXED_UPDATE_LIMIT :: 4
RENDER_SWAPCHAIN_IMAGES :: 3
RENDER_INPUT_FREQUENCY :: 3
WORLDS_TERRAIN_LIMIT :: 10
WORLDS_ENTITIES_LIMIT :: 1024
